[project]
name = "rivtlib-package"
version = "0.5.0"
description = "install rivtlib-package or rivt-project as extra"
authors = [{ name = "rod holland", email = "rod.h.holland@gmail.com" }]
requires-python = ">=3.11"
dependencies = [
    "tabulate>=4.4.0",
    "pillow>=11.2.1",
    "docutils>=0.21.2",
    "matplotlib>=3.10.1",
    "sympy>=1.13.3",
    "numpy>=2.2.5",
    "pandas>=2.2.3",
    "jupyterlab>=4.4.1",
    "rivtlib @ git+https://github.com/rivtlib-dev/rivtlib",
]
[project.optional-dependencies]
rivt = [
    "Sphinx>=8.2.3",
    "pydata-sphinx-theme>=0.16.1",
    "reportlab>=4.4.0",
    "rst2pdf>=2.2.5",
    "pypdf>=1.0.3",
]
[build-system]
requires = [
    "hatchling",
] # Example build backend, can be setuptools, poetry, etc.
build-backend = "hatchling.build"
